language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

before_install:
  - pip --quiet install docutils
  - pip --quiet install Pygments==1.6
  - pip --quiet install coverage
  - coverage --version
  - sudo apt-get --quiet=2 install patchutils

install:
  - python setup.py --quiet install

script:
  - make test
