language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install -r requirements.txt
  - coverage --version
  - sudo apt-get update
  - sudo apt-get --quiet=2 install patchutils
  - python setup.py --quiet install

script:
  - make test
