language: python

python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

before_install:
    - pip --quiet install coverage
    - coverage --version

install:
    - python setup.py --quiet install

script:
    - make test
